name: jobs examples
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artifact for reuse (changed2)
        run: echo “Full featured artifact” > build-result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build-result.txt

  deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Reviewers
    steps:
      - uses: actions/download-artifact@v4
        with:
            name: build-result
            path: build-result.txt
      - name: step do deploy
        run: echo Hello, world! Deploy.
