name: Deploy Frontend to Elastic Beanstalk

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 436486625381
  PROJECT_NAME: conchayoro
  MODULE_NAME: frontend
  IMAGE_TAG: latest
  ECR_REPO: 436486625381.dkr.ecr.us-east-1.amazonaws.com/conchayoro/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login no Amazon ECR
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

    - name: Build imagem Docker
      run: docker build -t $ECR_REPO:$IMAGE_TAG frontend/

    - name: Push da imagem para o ECR
      run: docker push $ECR_REPO:$IMAGE_TAG

    - name: Gerar Dockerrun.aws.json
      run: |
        echo '{
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "'$ECR_REPO':'$IMAGE_TAG'",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "80"
            }
          ]
        }' > Dockerrun.aws.json

    - name: Inicializar EB CLI
      run: |
        cd frontend
        eb init $PROJECT_NAME --platform docker --region $AWS_REGION --quiet
        eb use frontend --quiet

    - name: Deploy para Elastic Beanstalk
      run: eb deploy --staged --label "v-${{ github.run_number }}" --verbose
      working-directory: frontend
