name: pipeline-ecr-ebs

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  TAG: latest
  STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Docker build
      run: docker build -t $MODULE_FULLNAME $MODULE_NAME

    - name: Docker tag
      run: |
        docker tag $MODULE_FULLNAME:$TAG \
        $REGISTRY_URL/$MODULE_FULLNAME:$TAG

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $REGISTRY_URL

    - name: Docker push to ECR
      run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG

    - name: Replace placeholders in Dockerrun.aws.json
      run: |
        sed -i "s|<AWS_ACCOUNT_ID>|${AWS_ACCOUNT_ID}|g" Dockerrun.aws.json
        sed -i "s|<PROJECT_NAME>|${PROJECT_NAME}|g" Dockerrun.aws.json
        sed -i "s|<MODULE_NAME>|${MODULE_NAME}|g" Dockerrun.aws.json
        sed -i "s|<TAG>|${TAG}|g" Dockerrun.aws.json

    - name: Print final Dockerrun.aws.json
      run: cat Dockerrun.aws.json

    - name: Install EB CLI
      run: |
        pip install awsebcli --upgrade

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init $PROJECT_NAME --platform docker --region $AWS_REGION
        eb use $MODULE_NAME
        eb deploy --verbose
