name: pipeline-ecr-ebs

on:
  push:
    branches: [ main ]
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  TAG: latest
  STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build Docker image
        run: docker build -t $MODULE_FULLNAME $MODULE_NAME

      - name: Tag da imagem para o ECR
        run: |
          docker tag $MODULE_FULLNAME:$TAG \
          $REGISTRY_URL/$MODULE_FULLNAME:$TAG

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $REGISTRY_URL

      - name: Push imagem para o ECR
        run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG

      - name: Upload dos arquivos de configuração do EB
        uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download dos arquivos de configuração do EB
        uses: actions/download-artifact@v4
        with:
          name: ebconfig
          path: .

      - name: Substituir variáveis no Dockerrun.aws.json
        run: |
          sed -i "s|<AWS_ACCOUNT_ID>|$AWS_ACCOUNT_ID|" Dockerrun.aws.json
          sed -i "s|<PROJECT_NAME>|$PROJECT_NAME|" Dockerrun.aws.json
          sed -i "s|<MODULE_NAME>|$MODULE_NAME|" Dockerrun.aws.json
          sed -i "s|<TAG>|$TAG|" Dockerrun.aws.json

      - name: Instalar Python e EB CLI
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Deploy para o Elastic Beanstalk
        run: eb deploy --verbose
